import { Service } from "../types/service";

export type RootStackParamList = {
    Splash: undefined;
    Welcome: undefined;
    Login: undefined;
    Register: undefined;
    Main: undefined;
    AdminMain: undefined;
    ServiceDetail: { service: any };
    Notifikasi: undefined;
    NotificationDetail: { id: string };
    MapEmergency: { onLocationSelect: (loc: any) => void };
    ProfileDetail: undefined;
    OtpVerification: { email: string };
    Berita: undefined;
    RegisterForm: { formData: any };
    ForgotPassword: undefined;
    ResetPassword: { email: string };
    ServiceHistory: undefined;
    ComplaintHistory: undefined;
    Pengaturan: undefined;
    EventList: undefined;
    DinasList: undefined;
    DinasDetail: { item?: any; id?: string | number };
    CreateEvent: undefined;
    CreateDinas: undefined;
    CreateLayanan: undefined;
    LayananList: undefined;
    LayananDetail: { item?: any; id?: string | number };
    CreatePengaduan: undefined;
    PengaduanList: undefined;
    PengaduanDetail: { item: any; id?: string | number };
    AdminPengaduanList: undefined;
    AdminPengaduanDetail: { item: any };
    EmergencyDetail: { report: any };
    DaruratList: undefined;
    EventDetail: { event: any };
    AnalisisAIList: undefined;
    CreateAnalisisAI: undefined;
    AnalisisAIDetail: { item: any };
    CreateBerita: { item?: any };
    AdminBeritaList: undefined;
    AdminBeritaDetail: { item: any };
    Webview: { url: string; title?: string; isAuth?: boolean };
    CompleteProfile: undefined;
    SamsatKeliling: undefined;
    CreateSamsat: { item?: any };
    AsdaList: undefined;
    AsdaDetail: { id: number };
    CreateAsda: { item?: any };
    CamatList: undefined;
    CamatDetail: { id: number };
    CreateCamat: { item?: any };
    AllFeatures: undefined;
    Transportasi: undefined;
    Ambulans: undefined;
    Pajak: undefined;
    CctvMonitor: undefined;
};

export type BottomTabParamList = {
    Beranda: undefined;
    Layanan: { query?: string } | undefined;
    Darurat: undefined;
    Berita: undefined;
    Profil: undefined;
    Scan: undefined;
};